### ISSUE TITLE
Problem Sending RF signal

### ISSUE THREAD

**Issue by fermosan** [olivluca/tuya_rf#1]
Hello,
i am trying your code with a COOLSEER WIFI IR+RF CONTROLLER BLACK (also CMT BASED) and i have trouble forming the PWM Packet.
You can see the original packet here: 
https://triq.org/pdv/#AAB037060612C4016C02D405E01F68BE7C8392A1A1A19292A1929292A1A1A1A1A192A1A192A1A1A1A1A1929292929292A1A1929292A1929292A455+AAB037060512C4016C02D405E01F68BE7C8392A1A1A19292A1929292A1A1A1A1A192A1A192A1A1A1A1A1929292929292A1A1929292A1A1A1A19455+AAB037060112C4016C02D405E01F68BE7C8392A1A1A19292A1929292A1A1A1A1A192A1A192A1A1A1A1A1929292929292A1A1929292A1A1A1A19555

The output packet is: 
https://triq.org/pdv/#AAB01308010A3C062C02CC01BC28881280011CFFFF8555+AAB06408010A3C062C02CC01BC28881280011CFFFF96A2B2B2B6A6A2B6A6A6A2B2B2B2B2B6A2B2B6A2B2B2B2B2B6A6A6A6A6A6A2B2B6A6A6A2B6A6A6A2B6A2B2B2B6A6A2B6A6A6A2B2B2B2B2B6A2B2B6A2B2B2B2B2B6A6A6A6A6A6A2B2B6A6A6A2B2B2B2B6A2C755

For the code i am using:
4808,-1508,364,-724,724,-364,724,-364,724,-364,364,-724,364,-724,724,-364,364,-724,364,-724,364,-724,724,-364,724,-364,724,-364,724,-364,724,-364,364,-724,724,-364,724,-364,364,-724,724,-364,724,-364,724,-364,724,-364,724,-364,364,-724,364,-724,364,-724,364,-724,364,-724,364,-724,364,-724,724,-364,364,-724,364,-724,364,-724,724,-364,364,-724,364,-724,364,-724,724,-364,364,-724,724,-364,724,-364,724,-364,364,-724,364,-724,724,-364,364,-724,364,-724,364,-724,724,-364,724,-364,724,-364,724,-364,724,-364,364,-724,724,-364,724,-364,364,-724,724,-364,724,-364,724,-364,724,-364,724,-364,364,-724,364,-724,364,-724,364,-724,364,-724,364,-724,364,-724,724,-364,364,-724,364,-724,364,-724,724,-364,724,-364,724,-364,724,-364,364,-724

Do you have any ideas ? And by the way, are those options configurable in esphome yaml ?

 start_pulse_min, start_pulse_max, end_pulse:

**Comment by fermosan** [comment]
Libretiny included your patch for rf capture. The captured raw works fine. I am closing this.

**Comment by olivluca** [comment]
Glad it worked for you, and, yes, those options should be configurable (unless there is a bug somewhere :wink: )
