### ISSUE TITLE
confirmed working on a generic model

### ISSUE THREAD

**Issue by ntzb** [olivluca/tuya_rf#3]
just wanted to say **thanks** for this module!
I confirm this is working with a generic ir+rf with the same chips (cbu, sh4) that I got from aliexpress.

I'm only interested in the RF part, so that's what I tested. 
the codes were learned using the tuya app, and pulled using their web developer api portal (the device is on a different subnet due to vlan, so tinytuya could not connect to it).
so essentially what I tested is the transmitting of RF.

here are some pics of my model:
![20241202_110312](https://github.com/user-attachments/assets/73bdf79e-b23d-491f-bd9a-747c1d2ee48d)
![20241202_110413](https://github.com/user-attachments/assets/b749e55b-af35-4230-8b4a-d7a92697b7cc)
![20241202_110550](https://github.com/user-attachments/assets/54ee9981-79cd-4d47-9627-c58b6374e018)

**Comment by olivluca** [comment]
Thank you for telling me it works for you. In theory you should be able to learn the raw codes with the module (even though I learned mines with tuya too).
